### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jnordberg** [eosnewyork/eos-transit#12]
Just noticed that version got bumped from 2.x to 3.x and not long ago it went from 1.x to 2.x. It would be great if there was a changelog detailing what APIs are being broken with the major releases (assuming you're following semver).

**Comment by warrick-eosny** [comment]
Sorry about that, will make sure we add and maintain one. Will update this issue when done.

**Comment by warrick-eosny** [comment]
CHANGELOG.md added to root. I'll probably improve on the process as I move forward. Thanks for pushing me to do this :)
