### ISSUE TITLE
transit-react-basic doesn't compile

### ISSUE THREAD

**Issue by sgehrman** [eosnewyork/eos-transit#25]
Failed to compile.

/home/steve/Documents/GitHub/aikon/eos-transit/examples/transit-react-basic/src/initDefaultAccessContext.ts
(29,10): Argument of type '{ exchangeTimeout: number; transport: "TransportWebusb"; name: string; shortName: string; id: string; }' is not assignable to parameter of type 'ledgerWalletProviderOptions'.
  Types of property 'transport' are incompatible.
    Type '"TransportWebusb"' is not assignable to type '"TransportWebAuthn" | "TransportU2F" | "TransportWebBLE" | undefined'.

**Comment by warrick-eosny** [comment]
Sorry it's because I'm working on the webusb piece. 

Deleting this line should fix it for you

https://github.com/eosnewyork/eos-transit/blob/master/examples/transit-react-basic/src/initDefaultAccessContext.ts#L29

I'll commit a fix later tonight.

**Comment by sgehrman** [comment]
Thanks.
